# Generated by Django 2.2.3 on 2019-07-28 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('logo', models.CharField(max_length=500)),
                ('cote', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Math',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('id_equip1', models.IntegerField(verbose_name='Equipe 1')),
                ('id_equip2', models.IntegerField(verbose_name='Equipe 2')),
                ('scoreEq1', models.IntegerField()),
                ('scoreEq2', models.IntegerField()),
                ('idEquipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Equipe_math', to='MyApp.Equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
                ('logo', models.CharField(max_length=100)),
                ('ipEquipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Equipe_sport', to='MyApp.Equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte_client', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mise', models.IntegerField()),
                ('date_parie', models.DateTimeField(auto_now_add=True)),
                ('date_up', models.DateTimeField(auto_now=True)),
                ('idMath', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Math_parie', to='MyApp.Math')),
                ('idUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_parie', to='MyApp.Profile')),
            ],
        ),
    ]
