# Generated by Django 2.2.3 on 2019-07-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='math',
            name='scoreEq1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='math',
            name='scoreEq2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='compte_client',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='numero',
            field=models.IntegerField(null=True),
        ),
    ]
