# Generated by Django 2.2.3 on 2019-07-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_auto_20190729_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='cote',
            field=models.IntegerField(null=True),
        ),
    ]
