# Generated by Django 2.2.3 on 2019-07-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_auto_20190729_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='math',
            name='date_fin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='parier',
            name='mise',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='logo',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
