# Generated by Django 2.2.3 on 2019-07-29 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_auto_20190729_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='ipEquipe',
        ),
        migrations.AddField(
            model_name='equipe',
            name='ipSport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sport', to='MyApp.Sport'),
        ),
    ]
