# Generated by Django 2.2.3 on 2019-07-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_auto_20190730_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='math',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='math',
            name='date_fin',
        ),
        migrations.AddField(
            model_name='math',
            name='date_math',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='math',
            name='heure_debut',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='math',
            name='heure_fin',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
