# Generated by Django 2.2.3 on 2019-07-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_auto_20190730_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='date_add',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='math',
            name='date_math',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
