# Generated by Django 2.2.3 on 2019-07-31 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_auto_20190731_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipe',
            old_name='ipSport',
            new_name='idSport',
        ),
    ]
