# Generated by Django 2.2.3 on 2019-07-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0011_auto_20190731_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='math',
            name='scoreEq1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='math',
            name='scoreEq2',
            field=models.IntegerField(default=0),
        ),
    ]
