# Generated by Django 2.2.3 on 2019-07-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0012_auto_20190731_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='math',
            name='scoreEq1',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='math',
            name='scoreEq2',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
