# Generated by Django 2.2.3 on 2019-08-01 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0014_math_typesport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='idSport',
        ),
    ]
