# Generated by Django 2.2.3 on 2019-08-01 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0017_auto_20190801_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parier',
            name='idUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_parie', to=settings.AUTH_USER_MODEL),
        ),
    ]
