# Generated by Django 2.2.3 on 2019-08-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0018_auto_20190801_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='math',
            name='scoreEq1',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='math',
            name='scoreEq2',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='parier',
            name='idVictoir',
            field=models.IntegerField(null=True, verbose_name='parie pour '),
        ),
        migrations.AlterField(
            model_name='parier',
            name='mise',
            field=models.IntegerField(null=True, verbose_name='mise parie'),
        ),
    ]
