# Generated by Django 2.2.3 on 2019-08-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0020_auto_20190802_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='parier',
            name='resultat',
            field=models.BooleanField(default=False),
        ),
    ]
