# Generated by Django 2.2.3 on 2019-08-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0021_parier_resultat'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notif',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
