# Generated by Django 2.2.3 on 2019-08-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0022_profile_notif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='math',
            name='scoreEq1',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='math',
            name='scoreEq2',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
