# Generated by Django 2.2.3 on 2019-08-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0024_auto_20190802_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='compte_client',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
