# Generated by Django 2.2.3 on 2019-08-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0025_auto_20190802_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='parier',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
