# Generated by Django 2.2.3 on 2019-08-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0026_parier_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='parier',
            name='mathTerniner',
            field=models.BooleanField(default=False),
        ),
    ]
